### ISSUE TITLE
Driver Kontrol s4 mk1 MacBook m2

### ISSUE THREAD

**Issue by Djandersound1** [blaxpot/traktor-s4-mk1-midify#5]
"I bought the Kontrol S4 MK1 and saw that the driver is not compatible with the MacBook M2. Can you make the driver work? There are several people online looking for this; I believe you could make some money. I could also negotiate with you .

Please Help

You can send me an email or a WhatsApp message.

ander.3g@gmail.com

WhatsApp: +55 67 99250-1871"

**Comment by blaxpot** [comment]
This software depends on linux kernel modules, so it's unlikely to be helpful to Mac users (ARM or otherwise).

Unfortunately I'm not aware of any way you could easily get your controller to work on an ARM Mac, and it seems very unlikely that NI will release a driver at this stage.
